language: node_js
node_js:
  - "0.10"
install:
- npm -d install
- npm install -g grunt-cli
- npm install -g grunt
- npm install -g bower
- bower install
script:
- grunt travis
after_script:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
